version: '3.8'

services:
  # MongoDB база данных
  mongodb:
    image: mongo:7.0
    container_name: family-budget-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: family_budget
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - family-budget-network

  # Mongo Express для администрирования БД
  mongo-express:
    image: mongo-express:1.0.0
    container_name: family-budget-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - family-budget-network

  # Redis для кэширования (опционально)
  redis:
    image: redis:7.2-alpine
    container_name: family-budget-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "redis123"
    volumes:
      - redis_data:/data
    networks:
      - family-budget-network

  # Приложение (для продакшн сборки)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: family-budget-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/family_budget?authSource=admin
      MONGODB_DATABASE: family_budget
      REDIS_URL: redis://:redis123@redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - family-budget-network
    profiles:
      - production

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  family-budget-network:
    driver: bridge
