# Recording Rules for Family Budget Service
# Pre-computed metrics for better performance

groups:
  - name: family-budget-service.recording
    interval: 30s
    rules:
      # HTTP Request Rate
      - record: family_budget:http_request_rate
        expr: |
          rate(http_requests_total[5m])

      # HTTP Error Rate
      - record: family_budget:http_error_rate
        expr: |
          rate(http_requests_errors_total[5m]) /
          rate(http_requests_total[5m])

      # HTTP Response Time Percentiles
      - record: family_budget:http_request_duration_95p
        expr: |
          histogram_quantile(0.95,
            rate(http_request_duration_seconds_bucket[5m])
          )

      - record: family_budget:http_request_duration_99p
        expr: |
          histogram_quantile(0.99,
            rate(http_request_duration_seconds_bucket[5m])
          )

      # Database Operation Rate
      - record: family_budget:db_operation_rate
        expr: |
          rate(database_operations_total[5m])

      # Database Error Rate
      - record: family_budget:db_error_rate
        expr: |
          rate(database_operations_total{status="error"}[5m]) /
          rate(database_operations_total[5m])

      # Database Operation Duration Percentiles
      - record: family_budget:db_operation_duration_95p
        expr: |
          histogram_quantile(0.95,
            rate(database_operation_duration_seconds_bucket[5m])
          )

      # Business Metrics
      - record: family_budget:new_users_rate
        expr: |
          increase(users_total[1h])

      - record: family_budget:new_families_rate
        expr: |
          increase(families_total[1h])

      - record: family_budget:transaction_rate
        expr: |
          rate(transactions_total[5m])

      # Resource Utilization
      - record: family_budget:memory_utilization
        expr: |
          go_memstats_alloc_bytes{job="family-budget-service"} /
          go_memstats_sys_bytes{job="family-budget-service"}

      - record: family_budget:goroutine_count
        expr: |
          go_goroutines{job="family-budget-service"}

  - name: system.recording
    interval: 30s
    rules:
      # CPU Usage
      - record: system:cpu_usage
        expr: |
          100 - (
            avg by (instance) (
              rate(node_cpu_seconds_total{mode="idle"}[5m])
            ) * 100
          )

      # Memory Usage
      - record: system:memory_usage
        expr: |
          (
            node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes
          ) / node_memory_MemTotal_bytes * 100

      # Disk Usage
      - record: system:disk_usage
        expr: |
          100 - (
            node_filesystem_free_bytes{fstype!="tmpfs"} /
            node_filesystem_size_bytes{fstype!="tmpfs"} * 100
          )

  - name: mongodb.recording
    interval: 30s
    rules:
      # MongoDB Connection Usage
      - record: mongodb:connection_usage
        expr: |
          mongodb_connections{state="current"} /
          mongodb_connections{state="available"} * 100

      # MongoDB Operation Rate
      - record: mongodb:operation_rate
        expr: |
          rate(mongodb_op_counters_total[5m])

      # MongoDB Document Counts
      - record: mongodb:document_count_total
        expr: |
          sum(mongodb_collection_documents_total)

  - name: aggregated_metrics.recording
    interval: 1m
    rules:
      # Overall Service Health Score
      - record: family_budget:service_health_score
        expr: |
          (
            (1 - family_budget:http_error_rate) * 0.3 +
            (family_budget:http_request_duration_95p < 0.5) * 0.3 +
            (up{job="family-budget-service"}) * 0.2 +
            (up{job="mongodb-exporter"}) * 0.2
          ) * 100

      # SLI: Availability (last 5 minutes)
      - record: family_budget:sli_availability_5m
        expr: |
          avg_over_time(up{job="family-budget-service"}[5m])

      # SLI: Error Rate (last 5 minutes)
      - record: family_budget:sli_error_rate_5m
        expr: |
          family_budget:http_error_rate

      # SLI: Latency (95th percentile, last 5 minutes)
      - record: family_budget:sli_latency_95p_5m
        expr: |
          family_budget:http_request_duration_95p

      # SLO Compliance
      - record: family_budget:slo_availability_compliance
        expr: |
          family_budget:sli_availability_5m >= 0.999

      - record: family_budget:slo_error_rate_compliance
        expr: |
          family_budget:sli_error_rate_5m <= 0.001

      - record: family_budget:slo_latency_compliance
        expr: |
          family_budget:sli_latency_95p_5m <= 0.5